trunk/server/src/com/user/entity/User.java
package com.user.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{
	
	private Integer userId;    //自增主键
	private String userNo;     //用户编码
	private String userName;   //用户名称
	private String userStatus; //是否在职 1在职 0离职
	
	public User() {
		super();
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserNo() {
		return userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserStatus() {
		return userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

}

trunk/server/src/com/user/entity/json/Rest.java
package com.user.entity.json;

import java.util.Date;

public class Rest {
	
	private String key;
	
	private String value;
	
	private Date createTime;
	
	public Rest(String key , String value) {
		this.key = key;
		this.value = value;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
}

trunk/server/src/com/user/entity/json/RestObject.java
package com.user.entity.json;

public class RestObject {
	
	private int code;
	
	private String message;
	
	public RestObject (int code, String message) {
		this.message = message;
		this.code = code;
	}

	public int getCode() {
		return code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getMessage() {
		return message;
	}
	
	public void setMessage(String message) {
		this.message = message;
	}
}

trunk/server/src/com/user/entity/page/Page.java
/**
 * 
 */
package com.user.entity.page;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.beanutils.PropertyUtils;

/**
 * @author Administrator
 * 
 */
public class Page {

	/** 页码 */
	private Integer pageNo = 1; 
	/** 每页显示数量 */
	private Integer pageSize; 
	/** 页内数据集合 */
	private Collection<?> content; 
	/** 符合条件的总数量 */
	private Long totalRecNum; 
	/** 当前页开始的偏移量 */
	private Integer startIndex; 
	/** 查询条件 */
	private Map<Object, Object> condition = new HashMap<Object, Object>();

	public Map<Object, Object> getCondition() {
		return condition;
	}

	public Page(Integer pageNo)
	{
		super();
		this.pageNo=pageNo;
		this.pageSize=10;
	}
	
    public Page()
    {
    	this(1);
    }
	
	@SuppressWarnings("unchecked")
	public void setCondition(Object obj) {
		try {
			this.getCondition().putAll(PropertyUtils.describe(obj));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public Collection<?> getContent() {
		return content;
	}

	public void setContent(Collection<?> content) {
		this.content = content;
	}

	public Long getTotalRecNum() {
		return totalRecNum;
	}

	public void setTotalRecNum(Long totalRecNum) {
		this.totalRecNum = totalRecNum;
	}

	public Integer getTotalPageNum() {
		return totalRecNum%pageSize!=0?(int)(totalRecNum/pageSize+1):(int)(totalRecNum/pageSize);
	}

	public Boolean getPrePage() {
		return pageNo>1;
	}

	public Boolean getNextPage() {
		return pageNo<this.getTotalPageNum();
	}

	public Long getStartIndex() {
		return 1L*pageSize*(pageNo-1);
	}

	public Long getEndIndex() {
		return pageSize*pageNo>this.getTotalRecNum()?this.getTotalRecNum():pageSize*pageNo;
	}

	/**
	 * 去除警告的get方法
	 * @return
	 */
	protected Integer removeWaningMethod() {
		return this.startIndex;
	}
}

trunk/server/src/com/user/action/RestAction.java
package com.user.action;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.user.action.base.BaseAction;
import com.user.config.ConfigKeys;
import com.user.config.SystemConfig;
import com.user.entity.json.Rest;
import com.user.entity.json.RestObject;
import com.user.mapper.RestMapper;

@Controller
@RequestMapping("/rest")
public class RestAction extends BaseAction {

    private static final int SUCCESS_CODE = 0;
    private static final int VALIDATE_ERROR_CODE = 1;
    private static final int KEY_IS_NULL_CODE = 2;
    private static final int KEY_LARGE_ERROR_CODE = 3;
    private static final int VALUE_LARGE_ERROR_CODE = 4;
    private static final String SUCCESS_MESSAGE = "success";
    private static final String VALIDATE_ERROR_MESSAGE = "v is valid";
    private static final String KEY_IS_NULL_MESSAGE = "key is null";
    private static final String KEY_LARGE_ERROR_MESSAGE = "key too large";
    private static final String VALUE_LARGE_ERROR_MESSAGE = "value too large";

    private Logger logger = Logger.getLogger(RestAction.class);

    @Autowired
    private RestMapper mapper;

    /**
     * 返回JSON字符串
     * @param v
     * @param key
     * @param value
     * @return
     */
    @RequestMapping("/save")
    @ResponseBody
    public Object save(String v, String key, String value) {
        logger.info("v : " + v + " ; key : " + key + " , value : " + value);
        if (v == null || !v.equals(SystemConfig.getValue(ConfigKeys.REST_VALIDATE_KEY))) {
            return new RestObject(VALIDATE_ERROR_CODE, VALIDATE_ERROR_MESSAGE);
        }
        if (key == null) {
            return new RestObject(KEY_IS_NULL_CODE, KEY_IS_NULL_MESSAGE);
        } else if (key.length() >= 255) {
            return new RestObject(KEY_LARGE_ERROR_CODE, KEY_LARGE_ERROR_MESSAGE);
        }
        if (value != null && value.length() >= 255) {
            return new RestObject(VALUE_LARGE_ERROR_CODE, VALUE_LARGE_ERROR_MESSAGE);
        }
        mapper.saveDB(new Rest(key, value));
        return new RestObject(SUCCESS_CODE, SUCCESS_MESSAGE);
    }
}

trunk/server/src/com/user/action/UserAction.java
package com.user.action;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

import com.user.action.base.BaseAction;
import com.user.entity.User;
import com.user.entity.page.Page;
import com.user.service.UserService;

@Controller
@RequestMapping("/user")
public class UserAction extends BaseAction {

    @Autowired
    private UserService userService;

    /**
     * 创建用户输入
     * @return
     */
    @RequestMapping("/input")
    public String input() {
        return "user/input_user";
    }

    /**
     * 创建用户
     * @return
     */
    @RequestMapping("/add")
    public String create(User user) {
        userService.createUser(user);
        return "redirect:list.do";
    }

    /**
     * 根据id获取用户
     * @return 修改视图
     */
    @RequestMapping("/{userId}")
    public String preModify(@PathVariable("userId") int userId, Model model) {
        User user = userService.getUserById(userId);
        model.addAttribute("user", user);
        return "user/edit_user";
    }

    /**
     * 更新用户信息
     * @return 用户列表
     */
    @RequestMapping("/modify")
    public String modify(User user) {
        userService.modifyUser(user);
        return "redirect:list.do";
    }

    /**
     * 注销用户
     * @return 用户列表
     */
    @RequestMapping("/delete")
    public String remove(User user) {
        userService.removeUser(user);
        return "redirect:list.do";
    }

    /**
     * 用户列表
     * @return
     */
    @RequestMapping("/list")
    public String list(Model model, Page page, User queryUser) {
        if (queryUser != null) {
            page.setCondition(queryUser);
        }
        super.processPage(page);
        page = userService.loadAll(page);
        model.addAttribute("page", page);
        model.addAttribute("queryUser", queryUser);
        return "user/list_user";
    }
}

trunk/server/src/com/user/action/base/BaseAction.java
package com.user.action.base;

import javax.annotation.Resource;

import com.danga.MemCached.MemCachedClient;
import com.user.cache.ehcache.CacheUtil;
import com.user.entity.page.Page;

public abstract class BaseAction {
	/**
	 * 处理分页对象，将起始偏移量和每页显示个数防止到page的map里，传给MYBATIS
	 * @param page
	 */
	protected void processPage(Page page) {
		if (page != null) {
			page.getCondition().put("startIndex", page.getStartIndex());
			page.getCondition().put("pageSize", page.getPageSize());
		}
	}
	
	/**
	 * ehcache工具(手动使用)
	 */
	protected CacheUtil ehcache;
	@Resource(name="cacheUtil")
	public void setEhCache(CacheUtil cache) {
	   this.ehcache = cache;
	}
	
	/**
     * memcache工具(手动使用)
     */
    protected MemCachedClient memcache;
    @Resource(name="memCachedClient")
    public void setMemcache(MemCachedClient memcache) {
        this.memcache = memcache;
    }
}

trunk/server/src/com/user/action/loginAction.java
package com.user.action;

import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import com.user.action.base.BaseAction;
import com.user.config.MessageConfig;
import com.user.service.auth.AuthService;
import com.user.util.VerifyValidator;

@Controller
@RequestMapping("/admin")
public class loginAction extends BaseAction {
	
	@Autowired
	private AuthService authService;
	
	/**
	 * 登陆方法
	 * @param model
	 * @param request
	 * @return
	 */
	@RequestMapping("/login")
	public String login(Model model, HttpServletRequest request) {
		String username = request.getParameter("username");
		String password = request.getParameter("password");
		//验证码出错
		if (!VerifyValidator.validate(request, request.getParameter("rand"))) {
			model.addAttribute("errormsg", MessageConfig.getValue("verify_error"));
			return "index";
		}
		if (!authService.login(username, password)) {
			model.addAttribute("errormsg", MessageConfig.getValue("login_error"));
			return "index";
		}
		request.getSession().setAttribute("username", username);
		model.addAttribute("menustr", authService.getMenuStr(request.getContextPath()));
		return "main";
	}
	
	/**
	 * 退出系统
	 * @param request
	 * @return
	 */
	@RequestMapping("/logout")
	public String logout(HttpServletRequest request) {
		request.getSession().removeAttribute("username");
		return "index";
	}
}

trunk/server/src/com/user/servlet/BaseServlet.java
package com.user.servlet;

import javax.servlet.http.HttpServlet;
import org.apache.log4j.Logger;
import com.user.config.ConfigKeys;
import com.user.config.MessageConfig;
import com.user.config.SystemConfig;

/**
 * 系统BASESERVLET
 * @author Administrator
 *
 */
public class BaseServlet extends HttpServlet {
	
	private static final long serialVersionUID = 1L;
	
	private static final Logger logger = Logger.getLogger(BaseServlet.class);
       
    protected void startApplication() {
    	try {
    		logger.info("application initing.....");
        	String configFile = this.getServletConfig().getInitParameter(ConfigKeys.INITCONFIG_KEY);
        	String appPath = this.getServletContext().getRealPath("/");
        	SystemConfig.buildConfig(appPath, appPath + "WEB-INF\\classes\\" + configFile);
        	MessageConfig.buildConfig(appPath + "WEB-INF\\classes\\message.properties");
		} catch (Exception e) {
			logger.error("加载启动参数失败 " + e);
			e.printStackTrace();
		}
    }
    
    
}

trunk/server/src/com/user/servlet/InitServlet.java
package com.user.servlet;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;

/**
 * 系统初始化servlet
 * @author Administrator
 */
public class InitServlet extends BaseServlet {
	private static final long serialVersionUID = 1L;
       
	public void init(ServletConfig conf) throws ServletException {
		super.init();
		try {
			super.init(conf);
		} catch (ServletException e1) {
			e1.printStackTrace();
		}
		super.startApplication();
	}
}

trunk/server/WebRoot/jsp/user/edit_user.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@ include file="/jsp/common/tags.jsp"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<title>修改用户信息</title>
		<%@ include file="/jsp/common/header.jsp"%>
	</head>
	<body>
		<form action="<%=request.getContextPath() %>/user/modify.do">
			<div id="entry_header">修改用户信息</div>
			<div id="group_line">用户信息</div>
			<div id="group_entry">
			  <input type="hidden" name="userId" value="${user.userId}"/>
			  <ul style="padding: 5px;">
				<li>
					<span class="form_label">用户编码：</span>
					<span> <input type="text" name="userNo" value="${user.userNo}" size="32"maxlength="30"/> </span>
				</li>
				<li>
					<span class="form_label">用户名称：</span>
					<span> <input type="text" name="userName" value="${user.userName}" size="32"maxlength="30"/> </span>
				</li>
				<li>
					<span class="form_label">是否离职：</span>
					<span> 
						<input type="radio" name="userStatus" <c:if test="${user.userStatus=='1'}">checked</c:if> value="1">在职
						<input type="radio" name="userStatus" <c:if test="${user.userStatus=='0'}">checked</c:if> value="0">离职
					<br/></span>
				</li>
			  </ul>
			</div> 
		    <div id="submitDiv">
		        <input type="submit" value="修改用户信息"/>
	            <input type="reset" value="取消重写"/>
            </div>
		</form>
	</body>
</html>

trunk/server/WebRoot/jsp/user/input_user.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ include file="/jsp/common/tags.jsp"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<title>创建用户</title>
		<%@ include file="/jsp/common/header.jsp"%>

		<script type="text/javascript">
		   function validate()
		   {
		      if($("input[name = 'user.userNo']").val() == "")
		      {
		          alert("用户编号不能为空！");
		          return false;
		      }
		         
		         
		      if($("input[name = 'user.userName']").val() == "")
		      {
		          alert("用户名称不能为空！");
		          return false;
		      }
		      return true;
		   }
		   
        </script>
	</head>

	<body>
		<form action="<%=request.getContextPath() %>/user/add.do" onsubmit="return validate();">
			<div id="entry_header">创建用户</div>
			<div id="group_line">用户信息</div>
			<div id="group_entry">
			  <ul style="padding: 5px;">
				<li>
					<span class="form_label">用户编码：</span>
					<span> <input type="text" name="userNo" size="32" maxlength="30"/> </span>
				</li>
				<li>
					<span class="form_label">用户名称：</span>
					<span> <input type="text" name="userName" size="32"maxlength="30"/> </span>
				</li>
				<li>
					<span class="form_label">是否离职：</span>
					<span> 
					<input type="radio" name="userStatus" value="1">在职
					<input type="radio" name="userStatus" value="0">离职
					</span>
				</li>

			  </ul>
			</div> 
		    <div id="submitDiv">
	            <input type="submit" value="创建用户"/>
	            <input type="reset" value="取消重写"/>
            </div>
		</form>
	</body>
</html>

trunk/server/WebRoot/jsp/user/list_user.jsp
<%@ page language="java" import="java.util.*" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/jsp/common/tags.jsp"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>

		<title>用户列表</title>

		<meta http-equiv="pragma" content="no-cache">
		<meta http-equiv="cache-control" content="no-cache">
		<meta http-equiv="expires" content="0">
		<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
		<meta http-equiv="description" content="This is my page">

		<link rel="stylesheet" type="text/css"
			href="<c:url value='/css/application.css'/>">
		<script type="text/javascript" src="<c:url value="/js/common.js"/>"></script>
		<script type="text/javascript"
			src="<c:url value="/js/jquery-1.4.2.min.js"/>"></script>
		<style>
			.errorMessage {
				color: red;
			}
			
			.link,.link_span {
				color: blue;
				cursor: hand;
				text-decoration: underline;
			}
       </style>


	</head>


	<body>
		<div id="list_title">
			&gt;&gt; 用户信息
			<span id="switch_qry" onclick="switchQueryArea();"> [隐藏查询选择] </span>
		</div>
		<div id="query_area">
			<form action="<%=request.getContextPath() %>/user/list.do">
		    用户编码：<input type="text" class="text" name="userNo" value="${queryUser.userNo}"/>
             用户名称：<input type="text" class="text" name="userName"  value="${queryUser.userName}"/>
             是否在职：
             <select name="userStatus" class="text">
             	<option value="">请选择</option>
             	<option value="1" <c:if test="${queryUser.userStatus=='1'}">selected</c:if>>在职</option>
             	<option value="0" <c:if test="${queryUser.userStatus=='0'}">selected</c:if>>离职</option>
             </select>
			 <input type="submit" value=" 查 询 "/>
			 <input type="hidden" name="pageNo" value="${page.pageNo}"/>
			</form>
			
		</div>
		<c:if test="${page.content!='null'}">
			<table class="listable" cellspacing="0" cellpadding="0" border="0">
				<tr bgColor="blue">
					<th class="scol">
						序  号
					</th>
					<th class="scol">
						用户编码
					</th>
					<th class="scol">
						用户名称
					</th>
					<th class="scol">
						是否在职
					</th>
					<th>
						操作
					</th>
				</tr>
				<c:forEach var="user" items="${page.content}">
					<tr>
						<td>
							${user.userId} 
						</td>
						<td>
							${user.userNo} 
						</td>
						<td>
							${user.userName} 
						</td>
						<td>
								<c:if test="${user.userStatus == '1'}">在职</c:if> 
								<c:if test="${user.userStatus == '0'}">离职</c:if>
						</td>
						<td>
							<a href="<%=request.getContextPath()%>/user/${user.userId}.do">修改</a>

							<span class="link" title="删除用户"
								onclick="remove('${user.userName} ','${user.userId}');">删除
							</span>
						</td>
					</tr>
				</c:forEach>
			</table>
			<hr>

			<div id="page_nav">
				共
				<span class="page_text">${page.totalRecNum}</span>条&nbsp; 每页
				<span class="page_text">${page.pageSize}</span>条&nbsp; 当前列出 第
				<span class="page_text">${page.startIndex}</span>条 至 第
				<span class="page_text">${page.endIndex}</span>条&nbsp; 第
				<span class="page_text">${page.pageNo}/${page.totalPageNum}</span>页


				&nbsp;|&nbsp;
				<c:if test="${page.prePage!='null'}">
					<span class="link_span" onclick="gotoPage(1);" title="访问首页">首页</span>
				</c:if>
				<c:if test="${page.prePage!='null'}">
					<span class="link_span" onclick="gotoPage(${page.pageNo-1});"
						title="访问第${page.pageNo-1}页">上一页</span>
				</c:if>
				<c:if test="${page.nextPage!='null'}">
					<span class="link_span" onclick="gotoPage(${page.pageNo+1});"
						title="访问第${page.pageNo+1}页">下一页</span>
				</c:if>
				<c:if test="${page.nextPage!='null'}">
					<span class="link_span" onclick="gotoPage(${page.totalPageNum});"
						title="访问末页">末页</span>
				</c:if>

				&nbsp;|&nbsp; 跳转到
				<input type="text" id="pageNo" value="${page.pageNo}" class="text" size="2"
					style="text-align: right;" onKeyPress="onlyNumber();" />
				页&nbsp;
				<button onclick="gotoPage($('#pageNo').val());"
					style="height: 19px;">
					跳 转
				</button>

			</div>

		</c:if>
		<c:if test="${page.content=='null'}">
			<center>
				<div id="no_rec">
					<span class="failMsg">没有符合条件的帐户记录被找到！</span>
					<button onclick="history.go(-1);">
						返 回
					</button>
				</div>
			</center>
		</c:if>

	</body>
	<script type="text/javascript">
	    var cols=new Array("userId","userNo","userName","userStatus");
	    $(document).ready(           
            function()
            {
               var rIndexCol = $("#index").val();
               //alert(rIndexCol);
               var rtype = $("#colType").val();
              // alert(rtype); 
               if(rtype=="asc")
               {
                 $("th.scol").eq(parseInt(rIndexCol))
                       .append("<img style='margin-left:5px;' src='<c:url value="/pics/side_arrow_up.gif"/>'/>");
               }
               else
                 $("th.scol").eq(parseInt(rIndexCol))
                       .append("<img style='margin-left:5px;' src='<c:url value="/pics/side_arrow_down.gif"/>'/>");
               
               
               $("th.scol").css("cursor","hand")
                      .bind(
                           "mouseover",
                           function(){
                              $(this).css("text-decoration","underline");
                           }
                      )
                     .bind(
                           "mouseout",
                           function(){
                              $(this).css("text-decoration","");
                           }
                      )
                      .bind(
                            "click",
                            function(){
                                var colIndexTemp=$("th.scol").index($(this));
                                var colNameTemp=cols[$("th.scol").index($(this))];
                                var sortedTypeTemp="";
                                if(parseInt(rIndexCol)!= $("th.scol").index($(this)))
                                   sortedTypeTemp="asc";
                                else
                                   sortedTypeTemp=rtype=="asc"?"desc":"asc"
                                
                                //alert(colIndexTemp+"|"+colNameTemp+"|"+sortedTypeTemp);                              
                                $("#index").attr('value',colIndexTemp);
                                $("#colName").attr('value',colNameTemp);
                                $("#colType").attr('value',sortedTypeTemp);
                                $("input[name='pageNo']").attr('value',1);
                                
                                document.forms[0].submit();
                            }
                           );	                                                                                                                            
            }
          
         );
	    function remove(name,id)
        {
          if(confirm("真的要注销用户[" + name + "]吗？"))
             location.href="<%=request.getContextPath() %>/user/delete.do?userId="+id;         
        }


         function switchQueryArea()
         {
            $('#query_area').toggle();
            if($('#query_area').css('display')=='none')
               $('#switch_qry').text(' [显示查询选择] ');
            else
               $('#switch_qry').text(' [隐藏查询选择] ');
         }
        function gotoPage(pageNo)
         {
            if(pageNo<1 || pageNo>${page.totalPageNum})
            {
              alert("页面编号输入错误！范围为1-${page.totalPageNum}");
              $('#pageNo').get(0).select();
              return;
            }
            //alert($("input[name='page.pageNo']").val());
            
            $("input[name='pageNo']").attr('value',pageNo);
            document.forms[0].submit();
         }
         
         function newQuery()
         {
           $("input[name='pageNo']").attr('value','1');
                        return true;
         }
   </script>
</html>